### ISSUE TITLE
Website not mobile-friendly

### ISSUE THREAD

**Issue by mschrimpf** [brain-score/brain-score.web#9]
Table doesn't fit on screen yet there is no horizontal scrollbar.
Tested on Firefox.

Possible solution (wild guess):

```css
body {
  overflow:auto;
}
```

(ported from https://github.com/brain-score/brain-score/issues/115)
